name: PCRemote

options:
  bundleIdPrefix: com.pcremote

targets:
  PCRemote:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: PCRemote
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pcremote.iphone
        INFOPLIST_FILE: PCRemote/Info.plist
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
